# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import directors_pb2 as directors__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DirectorsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_directors = channel.unary_stream(
                '/directors.DirectorsService/get_directors',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=directors__pb2.Director.FromString,
                )
        self.get_director = channel.unary_unary(
                '/directors.DirectorsService/get_director',
                request_serializer=directors__pb2.DirectorId.SerializeToString,
                response_deserializer=directors__pb2.Director.FromString,
                )


class DirectorsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_directors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_director(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectorsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_directors': grpc.unary_stream_rpc_method_handler(
                    servicer.get_directors,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=directors__pb2.Director.SerializeToString,
            ),
            'get_director': grpc.unary_unary_rpc_method_handler(
                    servicer.get_director,
                    request_deserializer=directors__pb2.DirectorId.FromString,
                    response_serializer=directors__pb2.Director.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'directors.DirectorsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DirectorsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_directors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/directors.DirectorsService/get_directors',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            directors__pb2.Director.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_director(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/directors.DirectorsService/get_director',
            directors__pb2.DirectorId.SerializeToString,
            directors__pb2.Director.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
