# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: directors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64irectors.proto\x12\tdirectors\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x08\x44irector\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\"\x18\n\nDirectorId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x8e\x01\n\x10\x44irectorsService\x12>\n\rget_directors\x12\x16.google.protobuf.Empty\x1a\x13.directors.Director0\x01\x12:\n\x0cget_director\x12\x15.directors.DirectorId\x1a\x13.directors.Directorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'directors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIRECTOR._serialized_start=59
  _DIRECTOR._serialized_end=112
  _DIRECTORID._serialized_start=114
  _DIRECTORID._serialized_end=138
  _DIRECTORSSERVICE._serialized_start=141
  _DIRECTORSSERVICE._serialized_end=283
# @@protoc_insertion_point(module_scope)
