from database.database import Database

if __name__ == "__main__":
    dataBase = Database()
    dataBase.create_tables()
    dataBase.add_movie('The Shawshank Redemption',"Historia dwóch więźniów, Andy'ego i Reda, którzy przebywają w więzieniu Shawshank. Andy próbuje pomóc swoim towarzyszom więzienia, podczas gdy Red stara się przetrwać i dostać się do dobrej grupy",'Frank','Darabont','Dramat')
    dataBase.add_movie('The Godfather',"Historia rodziny Corleone, mafijnej rodziny z Nowego Jorku, która próbuje utrzymać swój wpływ i pozycję",'Francis','Ford Coppola','Gangsterski')
    dataBase.add_movie('The Dark Knight',"Batman staje do walki z przestępczym genialnym psychopatą Jokerem, który chce zniszczyć Gotham City",'Christopher','Nolan','Kryminał')
    dataBase.add_movie('Pulp Fiction',"Historie kilku osób, w tym pary mafiosów, pary gangusterów, kilku bohaterów przypadkowych i trójki hakerów, których losy splatają się w Los Angeles",'Quentin','Tarantino','Kryminał')
    dataBase.add_movie("Schindler's List","Historia biznesmena Oskara Schindlera, który próbuje ratować żydowskich pracowników podczas Holocaustu",'Steven','Spielberg','Wojenny')
    dataBase.add_movie("The Matrix","Film science-fiction opowiadający o rzeczywistości, w której ludzkość jest uwięziona w wirtualnej rzeczywistości przez maszyny, które rządzą światem","The Wachowski","Sisters","Science fiction")
    dataBase.add_movie("The Lord of the Rings: The Fellowship of the Ring","Film fantasy opowiadający o hobbie imieniem Frodo, który wyrusza w podróż, by zniszczyć pierścień, który daje jego posiadaczowi nieograniczoną moc","Peter","Jackson","Fantasy")
    dataBase.add_movie("Forrest Gump","Historia życia Forresta, prostego człowieka z niedosłuchem, który przeżywa wiele ważnych wydarzeń w historii USA w XX wieku","Robert","Zemeckis","Komedia")
    dataBase.add_movie("Incepcja","Film opowiada o zespołach specjalistów, którzy wykorzystują tajemniczą technologię do wchodzenia do snów ludzi, celem manipulowania ich marzeniami i ich podejrzeń","Christopher","Nolan","Science fiction")
    dataBase.add_movie("The Silence of the Lambs","Film sensacyjny opowiadający o śledztwie FBI w sprawie seryjnego mordercy, który zabija i zjada swoje ofiary, a także o agentce Clarice Starling, która próbuje rozwiązać tę zagadkę","Jonathan","Demme","Thriller")
    dataBase.add_movie("The Green Mile", "Film opowiadający o strażniku więziennym, który zaczyna wierzyć w nadprzyrodzoną moc skazańca oskarżonego o zabójstwo, który przebywa na karze śmierci", "Frank", "Darabont", "Dramat")
    dataBase.add_movie("The Prestige", "Film science fiction, opowiada o rywalizacji dwóch iluzjonistów, którzy próbują pokonać siebie nawzajem i zdobyć tajemnicę największego sztuczki", "Christopher", "Nolan", "Science fiction")
    dataBase.add_movie("The Departed", "Film kryminalny opowiadający o agentach pod przykrywką, którzy próbują przeniknąć do irlandzkiej mafii w Bostonie", "Martin", "Scorsese", "Kryminalny")
    dataBase.add_movie("The Lion King", "Animowany film opowiadający o młodym lwie, Simbie, który musi odzyskać swoje miejsce na czele stada po śmierci ojca", "Roger", "Allers", "Animacja")
    dataBase.add_movie("The Social Network", "Film opowiadający o powstaniu serwisu społecznościowego Facebook i jego twórcy Marku Zuckerbergu", "David", "Fincher", "Dramat")
    dataBase.add_movie("The Great Gatsby", "Film opowiadający o bogatym obywatelu Jay Gatsbym, który próbuje odzyskać swoją byłą miłość, Daisy Buchanan", "Baz", "Luhrmann", "Dramat")
    dataBase.add_movie("The Pianist", "Film opowiadający o życiu polskiego pianisty Władysława Szpilmana podczas II wojny światowej", "Roman", "Polanski", "Dramat")
    dataBase.add_movie("The Incredibles", "Animowany film opowiadający o rodzinie superbohaterów, która musi powrócić do walki z przestępcami po latach ukrywania się", "Brad", "Bird", "Animacja")
    dataBase.add_movie("The Big Lebowski", "Komediowy film noir opowiadający o nieporadnym, leniwym bowlerze Jeffie Leboswskim, który jest pomylony z bogatym Jeffem Leboswskim", "Joel", "Coen", "Komedia")
    dataBase.add_movie("The Terminator", "Film science fiction opowiadający o cyborgu, który przybywa z przyszłości, by zabić matkę przyszłego lidera rebelii przeciwko maszynom", "James", "Cameron", "Science fiction")
    dataBase.add_movie("The Elephant Man", "Film opowiadający o życiu Josepha Merricka, człowieka z niezwykłymi wadami genetycznymi, który zostaje wykorzystany jako atrakcja w cyrku", "David", "Lynch", "Dramat")
    dataBase.add_movie("The Grand Budapest Hotel", "Film komediowy opowiadający o przygodach dyrektora hotelu i jego pomocnika w Europie międzywojennej", "Wes", "Anderson", "Komedia")
    dataBase.add_movie("The Thing", "Film science fiction opowiadający o załodze stacji badawczej na Antarktydzie, która musi walczyć z obcym, który przybywa z kosmosu", "John", "Carpenter", "Science fiction")
    dataBase.add_movie("The Truman Show", "Film science fiction opowiadający o człowieku, którego całe życie jest transmitowane na żywo jako reality show, nie wiedząc o tym", "Peter", "Weir", "Science fiction")
    dataBase.add_movie("The Exorcist", "Film horror opowiadający o dziewczynce, która zostaje opętana przez demona i lekarze i księża próbują ją uwolnić", "William", "Friedkin", "Horror")
    dataBase.add_movie("The Godfather: Part II", "Kontynuacja historii rodziny Corleone, która koncentruje się zarówno na wydarzeniach z pierwszej części, jak i na młodości Don Corleone", "Francis Ford", "Coppola", "Dramat")
    dataBase.add_movie("The Shining", "Film horror opowiadający o rodzinie, która zostaje zamknięta w zimowym hotelu, gdzie zaczynają dziać się dziwne rzeczy", "Stanley", "Kubrick", "Horror")
    dataBase.add_movie("La La Land", "Film musicalowy opowiadający o miłości między aktorem a jazzową pianistką w Los Angeles", "Damien", "Chazelle", "Musical")
    dataBase.add_movie("The Revenant", "Film przygodowy opowiadający o trapperze, który przemierza dziewiczą prerię, by się zemścić na swoim byłym przyjacielu", "Alejandro", "González Iñárritu", "Przygodowy")
    dataBase.add_movie("Moonlight", "Film opowiadający o życiu młodego człowieka z Miami, który próbuje zrozumieć swoją tożsamość seksualną i relacje z rodziną", "Barry", "Jenkins", "Dramat")
    dataBase.add_movie("The Shape of Water", "Film fantasy opowiadający o przygodzie kobiety, która zakochuje się w potworze przetrzymywanym w laboratorium rządowym", "Guillermo del", "Toro", "Fantasy")
    dataBase.add_movie("Parasite", "Film kryminalny opowiadający o rodzinie biednych, która próbuje wkraść się do życia bogatej rodziny poprzez podstęp", "Bong Joon", "Ho", "Kryminalny")
    dataBase.add_movie("Nomadland", "Film opowiadający o kobiecie, która po utracie swojego domu i pracy, decyduje się na życie w vanie i podróżowanie po kraju jako nomadka", "Chloe", "Zhao", "Dramat")
    dataBase.add_movie("Promising Young Woman", "Film thriller opowiadający o kobiecie, która po traumie z przeszłości, przeprowadza swoiste dochodzenie w sprawie gwałtu", "Emerald", "Fennell", "Thriller")
    dataBase.add_movie("The Father", "Film dramatyczny opowiadający o relacji ojca z córką, gdy ten zaczyna chorować na demencję", "Florian", "Zeller", "Dramat")
    dataBase.add_movie("Sound of Metal", "Film opowiadający o perkusiście, który traci słuch i musi przestawić się na nowe życie", "Darius", "Marder", "Dramat")
    dataBase.add_movie("Minari", "Film opowiadający o rodzinie koreańskiej, która przeprowadza się na farmę w Arkansasie, by spełnić swoje marzenia", "Lee Isaac", "Chung", "Dramat")
    dataBase.add_movie("The Trial of the Chicago 7","Film opowiadający o procesie siedmiu aktywistów, oskarżonych o zamieszki podczas Demokratycznego Kongresu Narodowego w 1968 roku", "Aaron", "Sorkin", "Dramat")
    dataBase.add_movie("Tenet","Film science fiction opowiadający o agenta specjalnego, który jest zmuszony do udziału w operacji, która ma zapobiec III wojnie światowej przy użyciu inwersji czasu", "Christopher", "Nolan", "Science fiction")
    dataBase.add_movie("The Prom", "Film musicalowy opowiadający o grupie aktorów, którzy przyjeżdżają do małego miasteczka, by pomóc parze homoseksualnej zakochanych, którzy nie mogą pójść razem na bal maturalny", "Ryan", "Murphy", "Musical")
    dataBase.add_movie("The French Dispatch", "Film komediowy opowiadający o grupie dziennikarzy, którzy próbują ujawnić prawdę o różnych wydarzeniach na świecie", "Wes", "Anderson", "Komedia")
    dataBase.close_connection()