# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import genres_pb2 as genres__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GenresServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_genres = channel.unary_stream(
                '/genres.GenresService/get_genres',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=genres__pb2.Genre.FromString,
                )
        self.get_genre = channel.unary_unary(
                '/genres.GenresService/get_genre',
                request_serializer=genres__pb2.GenreId.SerializeToString,
                response_deserializer=genres__pb2.Genre.FromString,
                )


class GenresServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_genres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_genre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenresServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_genres': grpc.unary_stream_rpc_method_handler(
                    servicer.get_genres,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=genres__pb2.Genre.SerializeToString,
            ),
            'get_genre': grpc.unary_unary_rpc_method_handler(
                    servicer.get_genre,
                    request_deserializer=genres__pb2.GenreId.FromString,
                    response_serializer=genres__pb2.Genre.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genres.GenresService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenresService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_genres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/genres.GenresService/get_genres',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            genres__pb2.Genre.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_genre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genres.GenresService/get_genre',
            genres__pb2.GenreId.SerializeToString,
            genres__pb2.Genre.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
