# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genres.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgenres.proto\x12\x06genres\x1a\x1bgoogle/protobuf/empty.proto\"!\n\x05Genre\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x15\n\x07GenreId\x12\n\n\x02id\x18\x01 \x01(\x05\x32s\n\rGenresService\x12\x35\n\nget_genres\x12\x16.google.protobuf.Empty\x1a\r.genres.Genre0\x01\x12+\n\tget_genre\x12\x0f.genres.GenreId\x1a\r.genres.Genreb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genres_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=53
  _GENRE._serialized_end=86
  _GENREID._serialized_start=88
  _GENREID._serialized_end=109
  _GENRESSERVICE._serialized_start=111
  _GENRESSERVICE._serialized_end=226
# @@protoc_insertion_point(module_scope)
