# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import movies_pb2 as movies__pb2


class MoviesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_movies = channel.unary_stream(
                '/Movies.MoviesService/get_movies',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=movies__pb2.Movie.FromString,
                )
        self.get_movie = channel.unary_unary(
                '/Movies.MoviesService/get_movie',
                request_serializer=movies__pb2.MovieId.SerializeToString,
                response_deserializer=movies__pb2.Movie.FromString,
                )


class MoviesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_movies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_movie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoviesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_movies': grpc.unary_stream_rpc_method_handler(
                    servicer.get_movies,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=movies__pb2.Movie.SerializeToString,
            ),
            'get_movie': grpc.unary_unary_rpc_method_handler(
                    servicer.get_movie,
                    request_deserializer=movies__pb2.MovieId.FromString,
                    response_serializer=movies__pb2.Movie.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Movies.MoviesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MoviesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_movies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Movies.MoviesService/get_movies',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            movies__pb2.Movie.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_movie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Movies.MoviesService/get_movie',
            movies__pb2.MovieId.SerializeToString,
            movies__pb2.Movie.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
