# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\x12\x06Movies\x1a\x1bgoogle/protobuf/empty.proto\"^\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0b\x64irector_id\x18\x04 \x01(\x05\x12\x10\n\x08genre_id\x18\x05 \x01(\x05\"\x15\n\x07MovieId\x12\n\n\x02id\x18\x01 \x01(\x05\x32s\n\rMoviesService\x12\x35\n\nget_movies\x12\x16.google.protobuf.Empty\x1a\r.Movies.Movie0\x01\x12+\n\tget_movie\x12\x0f.Movies.MovieId\x1a\r.Movies.Movieb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIE._serialized_start=53
  _MOVIE._serialized_end=147
  _MOVIEID._serialized_start=149
  _MOVIEID._serialized_end=170
  _MOVIESSERVICE._serialized_start=172
  _MOVIESSERVICE._serialized_end=287
# @@protoc_insertion_point(module_scope)
